# Generated by Django 3.2 on 2022-01-24 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_one', models.TextField()),
                ('content_two', models.TextField()),
                ('title', models.CharField(choices=[('CLN', 'Cleaning'), ('JLY', 'Jealousy'), ('YNR', 'You never'), ('OTH', 'Other')], default='CLN', max_length=13)),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('url', models.SlugField(blank=True, editable=False, max_length=500, unique=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='content_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('quarrel_choice', models.CharField(choices=[('CTONE', 'Left'), ('UND', 'Undecided'), ('CTTWO', 'Right')], default='UND', max_length=14)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quarrelapp.post')),
            ],
            options={
                'ordering': ['date_published'],
            },
        ),
    ]
