# Generated by Django 3.2 on 2022-01-28 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarrelapp', '0003_remove_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content_one',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_one', to='quarrelapp.commentpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_two',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_two', to='quarrelapp.commentpost'),
        ),
    ]
