# Generated by Django 3.2 on 2022-01-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarrelapp', '0004_auto_20220128_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
