# Generated by Django 3.2 on 2022-01-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarrelapp', '0005_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_one',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_post_one', to='quarrelapp.commentpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_two',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_post_two', to='quarrelapp.commentpost'),
        ),
    ]
