# Generated by Django 3.2 on 2022-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarrelapp', '0007_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('CLN', 'Cleaning'), ('JLY', 'Jealousy'), ('YNR', 'You never'), ('OTH', 'Other')], default='CLN', max_length=13),
        ),
    ]
