# Generated by Django 3.2 on 2022-02-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarrelapp', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=120),
        ),
    ]
