# Generated by Django 3.2 on 2022-02-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarrelapp', '0010_alter_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='quarrel_choice',
        ),
    ]
